version: '3.6'
services:
  cod2_server:
    build: .
    image: "bgauduch/cod2_server:1.0"
    ports:
      - "20500:20500/udp"
      - "20510:20510/udp"
      - "28960:28960/tcp"
      - "28960:28960/udp"
    volumes:
      - ./cod2server/main:/server/main:ro
    restart: unless-stopped
