blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/bgauduch/call-of-duty-2-docker-server/discussions
    about: Ask questions or discuss ideas with the community
  - name: Documentation
    url: https://github.com/bgauduch/call-of-duty-2-docker-server/blob/master/README.md
    about: Read the project documentation
