name: 'Setup Configuration'
description: 'Loads centralized configuration from variants.json and sets outputs'

outputs:
  image_name:
    description: 'Docker image name from config'
    value: ${{ steps.config.outputs.image_name }}
  default_variant:
    description: 'Default variant tag'
    value: ${{ steps.config.outputs.default_variant }}
  artifact_retention_days:
    description: 'Artifact retention days from config'
    value: ${{ steps.config.outputs.artifact_retention_days }}
  variants_matrix:
    description: 'Full variants matrix JSON'
    value: ${{ steps.config.outputs.variants_matrix }}

runs:
  using: 'composite'
  steps:
    - name: Parse configuration
      id: config
      shell: bash
      run: |
        CONFIG_FILE=".github/config/variants.json"

        # Extract values from config
        IMAGE_NAME=$(jq -r '.image_name' "$CONFIG_FILE")
        DEFAULT_COD2_VERSION=$(jq -r '.default_variant.cod2_version' "$CONFIG_FILE")
        DEFAULT_LNXDED_TYPE=$(jq -r '.default_variant.cod2_lnxded_type' "$CONFIG_FILE")
        DEFAULT_VARIANT="${DEFAULT_COD2_VERSION}${DEFAULT_LNXDED_TYPE}"
        RETENTION_DAYS=$(jq -r '.artifact_retention_days' "$CONFIG_FILE")

        # Export as outputs
        echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT
        echo "default_variant=$DEFAULT_VARIANT" >> $GITHUB_OUTPUT
        echo "artifact_retention_days=$RETENTION_DAYS" >> $GITHUB_OUTPUT

        # Create matrix JSON for workflow consumption
        VARIANTS_MATRIX=$(jq -c '{include: .variants}' "$CONFIG_FILE")
        echo "variants_matrix=$VARIANTS_MATRIX" >> $GITHUB_OUTPUT

        echo "Configuration loaded:"
        echo "  Image name: $IMAGE_NAME"
        echo "  Default variant: $DEFAULT_VARIANT"
        echo "  Artifact retention: $RETENTION_DAYS days"
        echo "  Total variants: $(jq '.variants | length' "$CONFIG_FILE")"
